version: '3.7'

services:
  db:
    image: postgres:15
    container_name: db
    env_file:
      - .env
    volumes:
      - ./pg/pgdata:/var/lib/postgresql/data
      - ./config/config.yaml:/config/config.yaml
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
