#!/usr/bin/env bash

cd $AIRFLOW_HOME

rm -f "/workspace/awscliv2.zip"
rm -rf "/workspace/aws"

curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install

cd $AIRFLOW_HOME
