version: '3.7'

services:
  superset:
    build:
      context: .
      dockerfile: Dockerfile.superset
    container_name: superset
    restart: always
    environment:
      - SUPERSET_DATABASE_URI=${SUPERSET_DATABASE_URI}
    env_file:
      - .env
    ports:
      - ${SUPERSET_PORT}:${SUPERSET_PORT}
    volumes:
      - ./superset:/home/superset
    networks:
      - iowa_net

networks:
  iowa_net:
    external: true
